package com.ysc.apps.online.bean;

public class Discuss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.answer
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.user_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.video_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    private Long videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.id
     *
     * @return the value of discuss.id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.id
     *
     * @param id the value for discuss.id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.answer
     *
     * @return the value of discuss.answer
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.answer
     *
     * @param answer the value for discuss.answer
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.user_id
     *
     * @return the value of discuss.user_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.user_id
     *
     * @param userId the value for discuss.user_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.video_id
     *
     * @return the value of discuss.video_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public Long getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.video_id
     *
     * @param videoId the value for discuss.video_id
     *
     * @mbg.generated Tue Apr 30 20:53:00 CST 2019
     */
    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }
}