package com.ysc.apps.online.bean;

public class HomeworkAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_answer.id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_answer.answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_answer.user_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_answer.question_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_answer.state
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_answer.id
     *
     * @return the value of homework_answer.id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_answer.id
     *
     * @param id the value for homework_answer.id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_answer.answer
     *
     * @return the value of homework_answer.answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_answer.answer
     *
     * @param answer the value for homework_answer.answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_answer.user_id
     *
     * @return the value of homework_answer.user_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_answer.user_id
     *
     * @param userId the value for homework_answer.user_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_answer.question_id
     *
     * @return the value of homework_answer.question_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_answer.question_id
     *
     * @param questionId the value for homework_answer.question_id
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_answer.state
     *
     * @return the value of homework_answer.state
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_answer.state
     *
     * @param state the value for homework_answer.state
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}