package com.ysc.apps.online.dao;

import com.ysc.apps.online.bean.CourseChapter;
import com.ysc.apps.online.bean.CourseChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    long countByExample(CourseChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int deleteByExample(CourseChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int insert(CourseChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int insertSelective(CourseChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    List<CourseChapter> selectByExample(CourseChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    CourseChapter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseChapter record, @Param("example") CourseChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int updateByExample(@Param("record") CourseChapter record, @Param("example") CourseChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int updateByPrimaryKeySelective(CourseChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_chapter
     *
     * @mbg.generated Fri May 03 09:37:56 CST 2019
     */
    int updateByPrimaryKey(CourseChapter record);
}