package com.ysc.apps.online.dao;

import com.ysc.apps.online.bean.HomeworkQuestion;
import com.ysc.apps.online.bean.HomeworkQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    long countByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int deleteByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int insert(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int insertSelective(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    List<HomeworkQuestion> selectByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    HomeworkQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") HomeworkQuestion record, @Param("example") HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByExample(@Param("record") HomeworkQuestion record, @Param("example") HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByPrimaryKeySelective(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_question
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByPrimaryKey(HomeworkQuestion record);
}