package com.ysc.apps.online.dao;

import com.ysc.apps.online.bean.HomeworkAnswer;
import com.ysc.apps.online.bean.HomeworkAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    long countByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int deleteByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int insert(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int insertSelective(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    List<HomeworkAnswer> selectByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    HomeworkAnswer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") HomeworkAnswer record, @Param("example") HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByExample(@Param("record") HomeworkAnswer record, @Param("example") HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByPrimaryKeySelective(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_answer
     *
     * @mbg.generated Tue Apr 30 19:34:09 CST 2019
     */
    int updateByPrimaryKey(HomeworkAnswer record);
}