package com.ysc.apps.online.dao;

import com.ysc.apps.online.bean.Notices;
import com.ysc.apps.online.bean.NoticesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    long countByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int deleteByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int insert(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int insertSelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    List<Notices> selectByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    Notices selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int updateByExample(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int updateByPrimaryKeySelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Sun Apr 28 20:57:34 CST 2019
     */
    int updateByPrimaryKey(Notices record);
}